// app/api/mbaza/reports/export/pdf/route.ts
import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { buildReportData, type ReportType } from "@/lib/mbaza/reportBuilder";
import React from "react";

export async function GET(req: NextRequest) {
  const session = await getServerSession(authOptions);
  if (!session || !["ADMIN", "MBAZA_STAFF"].includes(session.user.role)) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  const { searchParams } = new URL(req.url);
  const type = (searchParams.get("type") ?? "completion") as ReportType;
  const from = searchParams.get("from") ?? undefined;
  const to = searchParams.get("to") ?? undefined;
  const groupId = searchParams.get("groupId") ?? undefined;
  const courseId = searchParams.get("courseId") ?? undefined;
  const language = searchParams.get("language") ?? undefined;

  const report = await buildReportData({ type, from, to, groupId, courseId, language });

  const { renderToBuffer, Document, Page, Text, View, StyleSheet } = await import("@react-pdf/renderer");

  const styles = StyleSheet.create({
    page: { padding: 40, fontFamily: "Helvetica", fontSize: 10, color: "#1a1a1a" },
    header: { marginBottom: 24 },
    title: { fontSize: 20, fontWeight: "bold", color: "#2d6a4f", marginBottom: 4 },
    subtitle: { fontSize: 10, color: "#666" },
    section: { marginBottom: 16 },
    sectionTitle: { fontSize: 12, fontWeight: "bold", color: "#2d6a4f", marginBottom: 6, borderBottom: "1px solid #e5e7eb", paddingBottom: 4 },
    summaryRow: { flexDirection: "row", marginBottom: 3 },
    summaryKey: { width: 180, fontWeight: "bold", color: "#374151" },
    summaryValue: { flex: 1, color: "#111" },
    table: { marginTop: 8 },
    tableHeader: { flexDirection: "row", backgroundColor: "#2d6a4f", padding: "4 6", marginBottom: 0 },
    tableHeaderCell: { color: "white", fontWeight: "bold", fontSize: 8, flex: 1 },
    tableRow: { flexDirection: "row", padding: "3 6", borderBottom: "0.5px solid #e5e7eb" },
    tableRowAlt: { flexDirection: "row", padding: "3 6", borderBottom: "0.5px solid #e5e7eb", backgroundColor: "#f9fafb" },
    tableCell: { fontSize: 8, flex: 1, color: "#374151" },
    footer: { position: "absolute", bottom: 24, left: 40, right: 40, textAlign: "center", color: "#9ca3af", fontSize: 8 },
    badge: { backgroundColor: "#d1fae5", color: "#065f46", padding: "1 4", borderRadius: 3, fontSize: 8 },
  });

  const doc = React.createElement(
    Document,
    null,
    React.createElement(
      Page,
      { size: "A4", style: styles.page },
      // Header
      React.createElement(
        View,
        { style: styles.header },
        React.createElement(Text, { style: styles.title }, "🌱 TwihugureHub"),
        React.createElement(Text, { style: { fontSize: 14, fontWeight: "bold", color: "#1a1a1a", marginTop: 6 } }, report.title),
        React.createElement(Text, { style: styles.subtitle }, `Generated: ${new Date(report.generatedAt).toLocaleString()}`),
        React.createElement(Text, { style: styles.subtitle }, `Generated by: ${session.user.name ?? session.user.email}`)
      ),
      // Filters
      (from || to || groupId) &&
        React.createElement(
          View,
          { style: styles.section },
          React.createElement(Text, { style: styles.sectionTitle }, "Report Filters"),
          from && React.createElement(View, { style: styles.summaryRow },
            React.createElement(Text, { style: styles.summaryKey }, "Date From:"),
            React.createElement(Text, { style: styles.summaryValue }, from)
          ),
          to && React.createElement(View, { style: styles.summaryRow },
            React.createElement(Text, { style: styles.summaryKey }, "Date To:"),
            React.createElement(Text, { style: styles.summaryValue }, to)
          )
        ),
      // Summary
      React.createElement(
        View,
        { style: styles.section },
        React.createElement(Text, { style: styles.sectionTitle }, "Summary Statistics"),
        ...Object.entries(report.summary).map(([k, v]) =>
          React.createElement(
            View,
            { key: k, style: styles.summaryRow },
            React.createElement(Text, { style: styles.summaryKey }, k.replace(/([A-Z])/g, " $1").replace(/^./, (s) => s.toUpperCase()) + ":"),
            React.createElement(Text, { style: styles.summaryValue }, String(v))
          )
        )
      ),
      // Data Table (up to 50 rows for PDF)
      report.rows.length > 0 &&
        React.createElement(
          View,
          { style: styles.section },
          React.createElement(Text, { style: styles.sectionTitle }, `Data (showing ${Math.min(50, report.rows.length)} of ${report.rows.length} rows)`),
          React.createElement(
            View,
            { style: styles.table },
            React.createElement(
              View,
              { style: styles.tableHeader },
              ...report.columns.map((col) =>
                React.createElement(Text, { key: col, style: styles.tableHeaderCell }, col.replace(/([A-Z])/g, " $1").trim())
              )
            ),
            ...report.rows.slice(0, 50).map((row, i) =>
              React.createElement(
                View,
                { key: i, style: i % 2 === 0 ? styles.tableRow : styles.tableRowAlt },
                ...report.columns.map((col) =>
                  React.createElement(Text, { key: col, style: styles.tableCell }, String(row[col] ?? ""))
                )
              )
            )
          )
        ),
      // Footer
      React.createElement(Text, { style: styles.footer }, "TwihugureHub · Confidential Report · Rwanda Agricultural Training Platform")
    )
  );

  const buffer = await renderToBuffer(doc);
  const filename = `${report.title.replace(/\s+/g, "_")}_${new Date().toISOString().slice(0, 10)}.pdf`;

  return new NextResponse(new Uint8Array(buffer), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${filename}"`,
    },
  });
}
