// app/api/mbaza/reports/export/xlsx/route.ts
import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { buildReportData, type ReportType } from "@/lib/mbaza/reportBuilder";

export async function GET(req: NextRequest) {
  const session = await getServerSession(authOptions);
  if (!session || !["ADMIN", "MBAZA_STAFF"].includes(session.user.role)) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  const { searchParams } = new URL(req.url);
  const type = (searchParams.get("type") ?? "completion") as ReportType;
  const from = searchParams.get("from") ?? undefined;
  const to = searchParams.get("to") ?? undefined;
  const groupId = searchParams.get("groupId") ?? undefined;
  const courseId = searchParams.get("courseId") ?? undefined;
  const language = searchParams.get("language") ?? undefined;

  const report = await buildReportData({ type, from, to, groupId, courseId, language });

  // Dynamic import to avoid SSR issues
  const XLSX = await import("xlsx");

  const wb = XLSX.utils.book_new();

  // Sheet 1: Summary
  const summaryData = [
    ["Report", report.title],
    ["Generated At", report.generatedAt],
    ["Generated By", session.user.name ?? session.user.email],
    [],
    ["Summary"],
    ...Object.entries(report.summary).map(([k, v]) => [k, String(v)]),
  ];
  const ws1 = XLSX.utils.aoa_to_sheet(summaryData);
  XLSX.utils.book_append_sheet(wb, ws1, "Summary");

  // Sheet 2: Raw Data
  const ws2 = XLSX.utils.json_to_sheet(report.rows);
  XLSX.utils.book_append_sheet(wb, ws2, "Raw Data");

  const buffer = XLSX.write(wb, { type: "buffer", bookType: "xlsx" });

  const filename = `${report.title.replace(/\s+/g, "_")}_${new Date().toISOString().slice(0, 10)}.xlsx`;

  return new NextResponse(buffer, {
    headers: {
      "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "Content-Disposition": `attachment; filename="${filename}"`,
    },
  });
}
